## Reading and writing files

numpy has many function to read and write files from/to disk.

In [1]:
import numpy as np

### Single array, binary format

In [2]:
a = np.random.rand(20)
a

array([0.86108466, 0.56066643, 0.51036061, 0.0194385 , 0.72525618,
       0.08979049, 0.78211461, 0.97890878, 0.38117603, 0.94499281,
       0.78822904, 0.74171703, 0.25663526, 0.79943052, 0.71753125,
       0.11069929, 0.91972603, 0.3287422 , 0.01077865, 0.60744089])

Save the array to a binary file named `a.npy`:

In [11]:
np.save('a', a)

In [12]:
ls

01_nparrays.ipynb        03_random.ipynb          MorrisMaria_Taller04.py
02_files.ipynb           04_plotting.ipynb        a.npy


Load the array back into memory:

In [13]:
a_copy = np.load('a.npy')

In [14]:
a_copy

array([0.86108466, 0.56066643, 0.51036061, 0.0194385 , 0.72525618,
       0.08979049, 0.78211461, 0.97890878, 0.38117603, 0.94499281,
       0.78822904, 0.74171703, 0.25663526, 0.79943052, 0.71753125,
       0.11069929, 0.91972603, 0.3287422 , 0.01077865, 0.60744089])

### Single array, text format

In [15]:
b = np.random.randint(0, 10, (5,3))
b

array([[7, 8, 4],
       [0, 5, 6],
       [9, 8, 8],
       [9, 0, 4],
       [4, 3, 2]])

The `savetxt` function saves arrays in a simple, textual format that is less effecient, but easier for other languges to read:

In [16]:
np.savetxt('b.txt', b)

In [17]:
ls

01_nparrays.ipynb        04_plotting.ipynb        b.txt
02_files.ipynb           MorrisMaria_Taller04.py
03_random.ipynb          a.npy


Now you could open the file `b.txt` and see the contents.
We can also use `loadtxt` to read the contents of the file.

In [18]:
np.loadtxt('b.txt')

array([[7., 8., 4.],
       [0., 5., 6.],
       [9., 8., 8.],
       [9., 0., 4.],
       [4., 3., 2.]])